[package]
name = "lindera-py"
version = "0.23.0"
edition = "2021"
description = "Python binding for Lindera."
documentation = "https://docs.rs/lindera-py"
homepage = "https://github.com/lindera-morphology/lindera-py"
repository = "https://github.com/lindera-morphology/lindera-py"
readme = "README.md"
keywords = ["morphological", "analysis", "library", "python"]
categories = ["text-processing"]
license = "MIT"

[lib]
name = "lindera_py"
crate-type = ["cdylib"]

[dependencies]
lindera = { version = "0.23.0", features = ["ipadic"] }
pyo3 = { version = "0.18.1", features = ["extension-module"] }
