[package]
name = "lindera-py"
version = "0.23.1"
edition = "2021"
description = "Python binding for Lindera."
documentation = "https://docs.rs/lindera-py"
homepage = "https://github.com/lindera-morphology/lindera-py"
repository = "https://github.com/lindera-morphology/lindera-py"
readme = "README.md"
keywords = ["morphological", "analysis", "library", "python"]
categories = ["text-processing"]
license = "MIT"

[lib]
name = "lindera_py"
crate-type = ["cdylib"]

[features]
default = []  # No directories included
ipadic = ["lindera/ipadic"]  # Include IPADIC dictionary (Japanese)
unidic = ["lindera/unidic"]  # Include UniDic dictionary (Japanese)
ko-dic = ["lindera/ko-dic"]  # Include ko-dic dictionary (Korean)
cc-cedict = ["lindera/cc-cedict"]  # Include CC-CEDICT dictionary (Chinese)
ipadic-filter = ["lindera/ipadic-filter"]  # Include filters for IPADIC
unidic-filter = ["lindera/unidic-filter"]  # Include filters for UniDic
ko-dic-filter = ["lindera/ko-dic-filter"]  # Include filters for ko-dic
cc-cedict-filter = ["lindera/cc-cedict-filter"]  # Include filters for CC-CEDICT
ipadic-compress = ["lindera/ipadic-compress"]  # Compress IPADIC
unidic-compress = ["lindera/unidic-compress"]  # Compress UniDic
ko-dic-compress = ["lindera/ko-dic-compress"]  # Compress ko-dic
cc-cedict-compress = ["lindera/cc-cedict-compress"]  # Compress CC-CEDICT

[dependencies]
pyo3 = { version = "0.18.2", features = ["extension-module"] }

lindera = "0.23.1"
