[package]
name = "lindera-py"
version = "0.18.0"
edition = "2021"
readme = "README.md"
keywords = ["morphological", "analysis", "library"]
categories = ["text-processing"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "lindera_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17.3", features = ["extension-module"] }
lindera = { git = "https://github.com/lindera-morphology/lindera.git", features = ["ipadic"] }
